### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by MagicKira** [Talyrius/TinyDPS#13]
234x integer overflow attempting to store 2205740058
[C]: in function `SetFormattedText'
TinyDPS\TinyDPS-0.942.lua:1418: in function `?'
TinyDPS\TinyDPS-0.942.lua:1459: in function `tdpsRefresh'
TinyDPS\TinyDPS-0.942.lua:1352: in function <TinyDPS\TinyDPS.lua:1343>
TinyDPS\TinyDPS-0.942.lua:2947: in function <TinyDPS\TinyDPS.lua:2946>

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "%i %i"
(*temporary) = 2205740058
(*temporary) = 2094787.5399902

**Comment by Talyrius** [comment]
Update to the newest version and use `/tdps reset` to clear the bad data.
