### ISSUE TITLE
[Suggestion] Custom Bar Textures

### ISSUE THREAD

**Issue by Imiona** [Talyrius/TinyDPS#15]
Hello

I would like to make a suggestion to add the Option to make your Custom Bar Textures (like the same way you already make your Custom Font). 

Thank you :)

**Comment by EdwinHauspie** [comment]
Not sure if this will happen, but if you really want it, you could try and change the _wglass.tga_ file in folder _\World of Warcraft\Interface\AddOns\TinyDPS\Textures_ with the texture you like. Just make sure the name is the same.
