### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by Daeveren** [Talyrius/TinyDPS#17]
No longer works with patch 8.0.1

**Comment by EdwinHauspie** [comment]
Here is a version of the main lua file you can use while waiting:
http://users.telenet.be/dropbox/TinyDPS.lua

**Comment by Daeveren** [comment]
Awesome, thank you kind stranger!

**Comment by Talyrius** [comment]
Fixed by [8.0.1.1](https://github.com/Talyrius/TinyDPS/tree/8.0.1.1). Download it [here](https://www.curseforge.com/wow/addons/tinydps).

**Comment by Daeveren** [comment]
Thanks @Talyrius
