### ISSUE TITLE
8.0.1 is here , let's update 

### ISSUE THREAD

**Issue by FedyTizaoui** [Talyrius/TinyDPS#18]
Hey , well the 8.0.1 is here and TinyDps Was the best addon for me in legion , a good companion so i wish you update the Addon so we can use it again 

thanks for the addon it's a really good 
see you in Azeroth

**Comment by nxrighthere** [comment]
Yea, I would love to see it updated.

**Comment by FedyTizaoui** [comment]
well i contacted him ( via email ) to ask is he updating the Addon or not , and the answer was Yes because he's playing to BFA so i think it's matter of time to get our update for TinyDps 

details & skada use a lot of memory when tinydps do the job with small amount of data ...

**Comment by spiralofhope** [comment]
Details! was recommended, and it is ridiculously overcomplicated.

**Comment by EdwinHauspie** [comment]
Here is a version of the main lua file you can use while waiting:
http://users.telenet.be/dropbox/TinyDPS.lua

**Comment by FedyTizaoui** [comment]
howbto use it ?

**Comment by EdwinHauspie** [comment]
Download/save the file in your tinydps addon folder. You must replcae the old one.

**Comment by FedyTizaoui** [comment]
thanks ^_^ 
my favorite meter rocks 😎❤️

**Comment by Talyrius** [comment]
See #17.
