### ISSUE TITLE
Shadowlands patch 9.0 error

### ISSUE THREAD

**Issue by Daeveren** [Talyrius/TinyDPS#24]
getting this error with patch 9.0
`Interface\AddOns\TinyDPS\TinyDPS.lua:1073: attempt to call method '?' (a nil value)`

**Comment by spiralofhope** [comment]
Replace `TinyDPS.lua` with [my edit](https://raw.githubusercontent.com/spiralofhope/TinyDPS/master/TinyDPS.lua
)

See also https://github.com/Talyrius/TinyDPS/pull/25
