### ISSUE TITLE
LibBossIds-1.0 Lua Error

### ISSUE THREAD

**Issue by Arcaila** [Talyrius/TinyDPS#27]
I saw this is on Curseforge, but it was lasted updated in 2017. I had issues with TinyDPS working, in general, a few weeks ago, and not sure if it's related to this error. If the library file isn't up to date, will this be an issue or will I just have to tell the game to ignore the error?

**Comment by Talyrius** [comment]
What's the error? I haven't received one, so you may installed the "nolib" (no libraries included) version.
![image](https://user-images.githubusercontent.com/1068810/108142662-0c06e980-707b-11eb-861c-211848058004.png)

**Comment by Arcaila** [comment]
Actually, I did have the Lib file but it was much older. Found the last one on the web dated 2017 and that seems to keep the error from popping up.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
